// ============================================================
// GAMES DATA — Mock data para desarrollo
// Última actualización: Marzo 2026
// ============================================================

export const GAMES_DATA = {

  // ──────────────────────────────────────────────────────────
  // 1. WUTHERING WAVES
  // ──────────────────────────────────────────────────────────
  "wuthering-waves": {
    id: "wuthering-waves",
    name: "Wuthering Waves",
    shortName: "WuWa",
    developer: "Kuro Games",
    publisher: "Kuro Games",
    currentVersion: "3.2",
    releaseDate: {
      android: "2024-05-22",
      ios: "2024-05-22",
      pc: "2024-05-22",
      ps5: "2025-05-22",
    },
    platforms: ["Android", "iOS", "PC", "PS5"],
    servers: ["Asia", "América", "Europa", "HMT (Hong Kong, Macao, Taiwán)"],
    officialSite: "https://wutheringwaves.kurogames.com",
    socialLinks: {
      twitter: "https://twitter.com/Wuthering_Waves",
      youtube: "https://www.youtube.com/@WutheringWaves",
      discord: "https://discord.gg/wutheringwaves",
      facebook: "https://www.facebook.com/WutheringWaves",
      instagram: "https://www.instagram.com/wutheringwaves_official",
      reddit: "https://www.reddit.com/r/WutheringWaves",
    },
    iconUrl: "https://static.wikia.nocookie.net/wutheringwaves/images/7/77/Item_Wuthering_Waves.png",
    bannerUrl: "https://static.wikia.nocookie.net/wutheringwaves/images/6/64/Wuthering_Waves_Key_Visual.png",
    description: "RPG de acción en mundo abierto ambientado en un mundo post-apocalíptico donde los Resonadores luchan contra los Ecos corrompidos.",
    genre: ["RPG de Acción", "Mundo Abierto", "Gacha"],
    rating: "12+",
    news: [
      {
        id: "ww-news-1",
        title: "Versión 3.2 en vivo: Sigrika y Qiuyuan se unen al roster",
        tag: "Nueva versión",
        date: "2026-02-26",
        imageUrl: "https://static.wikia.nocookie.net/wutheringwaves/images/6/64/Wuthering_Waves_Key_Visual.png",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1855",
      },
      {
        id: "ww-news-2",
        title: "Fase 2 de 3.2: Lynae, Zani y Phoebe disponibles en reinvocación",
        tag: "Banners",
        date: "2026-03-19",
        imageUrl: "https://static.wikia.nocookie.net/wutheringwaves/images/6/64/Wuthering_Waves_Key_Visual.png",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1870",
      },
      {
        id: "ww-news-3",
        title: "Códigos de emisión en vivo de la versión 3.2 — Canjéalos ya",
        tag: "Códigos",
        date: "2026-02-14",
        imageUrl: "https://static.wikia.nocookie.net/wutheringwaves/images/6/64/Wuthering_Waves_Key_Visual.png",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1840",
      },
      {
        id: "ww-news-4",
        title: "Actualización de optimización de la versión 3.1 — Notas del parche",
        tag: "Actualización",
        date: "2026-02-05",
        imageUrl: "https://static.wikia.nocookie.net/wutheringwaves/images/6/64/Wuthering_Waves_Key_Visual.png",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1820",
      },
      {
        id: "ww-news-5",
        title: "Guía de construcción de personajes — Emif y Luke temporada 3.1",
        tag: "Guía oficial",
        date: "2026-02-10",
        imageUrl: "https://static.wikia.nocookie.net/wutheringwaves/images/6/64/Wuthering_Waves_Key_Visual.png",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1830",
      },
      {
        id: "ww-news-6",
        title: "Wuthering Waves llega a Steam con críticas muy positivas",
        tag: "Anuncio",
        date: "2026-01-15",
        imageUrl: "https://static.wikia.nocookie.net/wutheringwaves/images/6/64/Wuthering_Waves_Key_Visual.png",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1800",
      },
    ],
  },

  // ──────────────────────────────────────────────────────────
  // 2. GENSHIN IMPACT
  // ──────────────────────────────────────────────────────────
  "genshin-impact": {
    id: "genshin-impact",
    name: "Genshin Impact",
    shortName: "Genshin",
    developer: "HoYoverse",
    publisher: "HoYoverse",
    currentVersion: "6.4",
    releaseDate: {
      android: "2020-09-28",
      ios: "2020-09-28",
      pc: "2020-09-28",
      ps4: "2020-09-28",
      ps5: "2021-04-28",
    },
    platforms: ["Android", "iOS", "PC", "PS4", "PS5"],
    servers: ["Asia", "América", "Europa", "TW/HK/MO"],
    officialSite: "https://genshin.hoyoverse.com",
    socialLinks: {
      twitter: "https://twitter.com/GenshinImpact",
      youtube: "https://www.youtube.com/@GenshinImpact",
      discord: "https://discord.gg/genshinimpact",
      facebook: "https://www.facebook.com/Genshinimpact",
      instagram: "https://www.instagram.com/genshinimpact",
      reddit: "https://www.reddit.com/r/Genshin_Impact",
    },
    iconUrl: "https://static.wikia.nocookie.net/gensin-impact/images/d/d4/Item_Genshin_Impact.png",
    bannerUrl: "https://upload-os-bbs.hoyolab.com/upload/2021/08/11/73565430/e42d7b5b5c92c8152c1e81fcfa9343ee_1549721727768564177.png",
    description: "RPG de acción en mundo abierto ambientado en el mundo de Teyvat, donde el Viajero busca a su hermano desaparecido atravesando siete naciones.",
    genre: ["RPG de Acción", "Mundo Abierto", "Gacha"],
    rating: "12+",
    news: [
      {
        id: "gi-news-1",
        title: "Versión 6.4 Luna V — Varka debuta junto a Flins en la Fase 1",
        tag: "Nueva versión",
        date: "2026-02-25",
        imageUrl: "https://upload-os-bbs.hoyolab.com/upload/2021/08/11/73565430/e42d7b5b5c92c8152c1e81fcfa9343ee_1549721727768564177.png",
        url: "https://genshin.hoyoverse.com/en/news/detail/121052",
      },
      {
        id: "gi-news-2",
        title: "Skirk y Escoffier regresan en la Fase 2 de la versión 6.4",
        tag: "Banners",
        date: "2026-03-17",
        imageUrl: "https://upload-os-bbs.hoyolab.com/upload/2021/08/11/73565430/e42d7b5b5c92c8152c1e81fcfa9343ee_1549721727768564177.png",
        url: "https://genshin.hoyoverse.com/en/news/detail/121280",
      },
      {
        id: "gi-news-3",
        title: "Evento Travelers' Tales — Fotografía y minijuegos en Mondstadt",
        tag: "Evento",
        date: "2026-02-25",
        imageUrl: "https://upload-os-bbs.hoyolab.com/upload/2021/08/11/73565430/e42d7b5b5c92c8152c1e81fcfa9343ee_1549721727768564177.png",
        url: "https://genshin.hoyoverse.com/en/news/detail/121100",
      },
      {
        id: "gi-news-4",
        title: "Códigos de retransmisión de la versión 6.4 — Canjea tus Primogemas",
        tag: "Códigos",
        date: "2026-02-21",
        imageUrl: "https://upload-os-bbs.hoyolab.com/upload/2021/08/11/73565430/e42d7b5b5c92c8152c1e81fcfa9343ee_1549721727768564177.png",
        url: "https://genshin.hoyoverse.com/en/news/detail/120950",
      },
      {
        id: "gi-news-5",
        title: "Genshin Impact — Guía completa del Abismo Espiral Marzo 2026",
        tag: "Guía oficial",
        date: "2026-03-01",
        imageUrl: "https://upload-os-bbs.hoyolab.com/upload/2021/08/11/73565430/e42d7b5b5c92c8152c1e81fcfa9343ee_1549721727768564177.png",
        url: "https://genshin.hoyoverse.com/en/news/detail/121200",
      },
      {
        id: "gi-news-6",
        title: "Notas completas del parche 6.4 — Mejoras y correcciones",
        tag: "Parche",
        date: "2026-02-25",
        imageUrl: "https://upload-os-bbs.hoyolab.com/upload/2021/08/11/73565430/e42d7b5b5c92c8152c1e81fcfa9343ee_1549721727768564177.png",
        url: "https://genshin.hoyoverse.com/en/news/detail/121060",
      },
    ],
  },

  // ──────────────────────────────────────────────────────────
  // 3. HONKAI: STAR RAIL
  // ──────────────────────────────────────────────────────────
  "honkai-star-rail": {
    id: "honkai-star-rail",
    name: "Honkai: Star Rail",
    shortName: "HSR",
    developer: "HoYoverse",
    publisher: "HoYoverse",
    currentVersion: "4.0",
    releaseDate: {
      android: "2023-04-26",
      ios: "2023-04-26",
      pc: "2023-04-26",
      ps5: "2023-10-11",
    },
    platforms: ["Android", "iOS", "PC", "PS5"],
    servers: ["Asia", "América", "Europa", "TW/HK/MO"],
    officialSite: "https://hsr.hoyoverse.com",
    socialLinks: {
      twitter: "https://twitter.com/HonkaiStarRail",
      youtube: "https://www.youtube.com/@HonkaiStarRail",
      discord: "https://discord.gg/honkaistarrail",
      facebook: "https://www.facebook.com/HonkaiStarRail",
      instagram: "https://www.instagram.com/honkaistarrail",
      reddit: "https://www.reddit.com/r/HonkaiStarRail",
    },
    iconUrl: "https://static.wikia.nocookie.net/houkai-star-rail/images/5/58/Item_Honkai_Star_Rail.png",
    bannerUrl: "https://upload-os-bbs.hoyolab.com/upload/2023/04/24/73565430/92946c65ba991669c5e3f43b67e7c913_5264003291244431952.png",
    description: "RPG estratégico por turnos donde el Trailblazer viaja por el cosmos a bordo del Astral Express, explorando mundos y enfrentando el Honkai.",
    genre: ["RPG por Turnos", "Estratégico", "Gacha"],
    rating: "12+",
    news: [
      {
        id: "hsr-news-1",
        title: "Versión 4.0 en vivo: Yao Guang y Sparxie en Planarcadia",
        tag: "Nueva versión",
        date: "2026-02-12",
        imageUrl: "https://upload-os-bbs.hoyolab.com/upload/2023/04/24/73565430/92946c65ba991669c5e3f43b67e7c913_5264003291244431952.png",
        url: "https://hsr.hoyoverse.com/en/news/detail/122050",
      },
      {
        id: "hsr-news-2",
        title: "Versión 4.1 confirmada: Ashveil debuta el 25 de Marzo 2026",
        tag: "Próxima versión",
        date: "2026-03-13",
        imageUrl: "https://upload-os-bbs.hoyolab.com/upload/2023/04/24/73565430/92946c65ba991669c5e3f43b67e7c913_5264003291244431952.png",
        url: "https://hsr.hoyoverse.com/en/news/detail/122310",
      },
      {
        id: "hsr-news-3",
        title: "Colaboración con Fortnite: outfits de Kafka y Blade disponibles",
        tag: "Colaboración",
        date: "2026-02-26",
        imageUrl: "https://upload-os-bbs.hoyolab.com/upload/2023/04/24/73565430/92946c65ba991669c5e3f43b67e7c913_5264003291244431952.png",
        url: "https://hsr.hoyoverse.com/en/news/detail/122150",
      },
      {
        id: "hsr-news-4",
        title: "Selector de personaje 5 estrellas gratis — Disponible hasta el fin de 4.2",
        tag: "Evento",
        date: "2026-02-12",
        imageUrl: "https://upload-os-bbs.hoyolab.com/upload/2023/04/24/73565430/92946c65ba991669c5e3f43b67e7c913_5264003291244431952.png",
        url: "https://hsr.hoyoverse.com/en/news/detail/122080",
      },
      {
        id: "hsr-news-5",
        title: "Mejoras para Sparkle y Black Swan con la versión 4.0",
        tag: "Actualización",
        date: "2026-02-12",
        imageUrl: "https://upload-os-bbs.hoyolab.com/upload/2023/04/24/73565430/92946c65ba991669c5e3f43b67e7c913_5264003291244431952.png",
        url: "https://hsr.hoyoverse.com/en/news/detail/122070",
      },
      {
        id: "hsr-news-6",
        title: "Retransmisión en vivo 4.1 — Todos los códigos y detalles del parche",
        tag: "Códigos",
        date: "2026-03-13",
        imageUrl: "https://upload-os-bbs.hoyolab.com/upload/2023/04/24/73565430/92946c65ba991669c5e3f43b67e7c913_5264003291244431952.png",
        url: "https://hsr.hoyoverse.com/en/news/detail/122300",
      },
    ],
  },

  // ──────────────────────────────────────────────────────────
  // 4. ZENLESS ZONE ZERO
  // ──────────────────────────────────────────────────────────
  "zenless-zone-zero": {
    id: "zenless-zone-zero",
    name: "Zenless Zone Zero",
    shortName: "ZZZ",
    developer: "HoYoverse",
    publisher: "HoYoverse",
    currentVersion: "2.6",
    releaseDate: {
      android: "2024-07-04",
      ios: "2024-07-04",
      pc: "2024-07-04",
      ps5: "2024-07-04",
    },
    platforms: ["Android", "iOS", "PC", "PS5"],
    servers: ["Asia", "América", "Europa", "TW/HK/MO"],
    officialSite: "https://zenless.hoyoverse.com",
    socialLinks: {
      twitter: "https://twitter.com/ZenlessZoneZero",
      youtube: "https://www.youtube.com/@ZenlessZoneZero",
      discord: "https://discord.gg/zenlesszonezero",
      facebook: "https://www.facebook.com/ZenlessZoneZero",
      instagram: "https://www.instagram.com/zenlesszonezero",
      reddit: "https://www.reddit.com/r/ZZZ_Official",
    },
    iconUrl: "https://static.wikia.nocookie.net/zenless-zone-zero/images/8/89/Item_Zenless_Zone_Zero.png",
    bannerUrl: "https://upload-os-bbs.hoyolab.com/upload/2022/05/13/73565430/328fc836c4b2b2ff513c1fdf4d538eec_8664124376510468305.png",
    description: "RPG de acción urbano ambientado en New Eridu, la última ciudad habitada, donde el Proxy ayuda a los Agentes a explorar las peligrosas Zonas Huecas.",
    genre: ["RPG de Acción", "Urbano", "Gacha"],
    rating: "12+",
    news: [
      {
        id: "zzz-news-1",
        title: "Versión 2.6 disponible — Nuevos agentes y contenido de historia",
        tag: "Nueva versión",
        date: "2026-02-05",
        imageUrl: "https://upload-os-bbs.hoyolab.com/upload/2022/05/13/73565430/328fc836c4b2b2ff513c1fdf4d538eec_8664124376510468305.png",
        url: "https://zenless.hoyoverse.com/en/news/detail/118050",
      },
      {
        id: "zzz-news-2",
        title: "Versión 2.7 llega el 24 de Marzo — Ediciones físicas para PS5 y Xbox",
        tag: "Próxima versión",
        date: "2026-03-10",
        imageUrl: "https://upload-os-bbs.hoyolab.com/upload/2022/05/13/73565430/328fc836c4b2b2ff513c1fdf4d538eec_8664124376510468305.png",
        url: "https://zenless.hoyoverse.com/en/news/detail/118320",
      },
      {
        id: "zzz-news-3",
        title: "Zenless Zone Zero anuncia edición física para Xbox Series X",
        tag: "Anuncio",
        date: "2026-03-08",
        imageUrl: "https://upload-os-bbs.hoyolab.com/upload/2022/05/13/73565430/328fc836c4b2b2ff513c1fdf4d538eec_8664124376510468305.png",
        url: "https://zenless.hoyoverse.com/en/news/detail/118290",
      },
      {
        id: "zzz-news-4",
        title: "Evento de temporada — Nuevos desafíos en el Hollow Zero",
        tag: "Evento",
        date: "2026-02-05",
        imageUrl: "https://upload-os-bbs.hoyolab.com/upload/2022/05/13/73565430/328fc836c4b2b2ff513c1fdf4d538eec_8664124376510468305.png",
        url: "https://zenless.hoyoverse.com/en/news/detail/118080",
      },
      {
        id: "zzz-news-5",
        title: "Guía completa de bangboos — Mejores combinaciones de equipo",
        tag: "Guía oficial",
        date: "2026-02-18",
        imageUrl: "https://upload-os-bbs.hoyolab.com/upload/2022/05/13/73565430/328fc836c4b2b2ff513c1fdf4d538eec_8664124376510468305.png",
        url: "https://zenless.hoyoverse.com/en/news/detail/118190",
      },
      {
        id: "zzz-news-6",
        title: "Retransmisión especial 2.7 — Códigos y nuevos personajes revelados",
        tag: "Códigos",
        date: "2026-03-14",
        imageUrl: "https://upload-os-bbs.hoyolab.com/upload/2022/05/13/73565430/328fc836c4b2b2ff513c1fdf4d538eec_8664124376510468305.png",
        url: "https://zenless.hoyoverse.com/en/news/detail/118340",
      },
    ],
  },

  // ──────────────────────────────────────────────────────────
  // 5. ARKNIGHTS: ENDFIELD
  // ──────────────────────────────────────────────────────────
  "arknights-endfield": {
    id: "arknights-endfield",
    name: "Arknights: Endfield",
    shortName: "Endfield",
    developer: "Hypergryph",
    publisher: "Hypergryph",
    currentVersion: "1.1",
    releaseDate: {
      android: "2026-01-22",
      ios: "2026-01-22",
      pc: "2026-01-22",
      ps5: "2026-01-22",
    },
    platforms: ["Android", "iOS", "PC", "PS5"],
    servers: ["Global"],
    officialSite: "https://endfield.arknights.com",
    socialLinks: {
      twitter: "https://twitter.com/ArknightsEN",
      youtube: "https://www.youtube.com/@Arknights",
      discord: "https://discord.gg/arknights",
      facebook: "https://www.facebook.com/ArknightsEN",
      instagram: "https://www.instagram.com/arknights_en",
      reddit: "https://www.reddit.com/r/arknightsendfield",
    },
    iconUrl: "https://static.wikia.nocookie.net/arknights/images/f/f6/Arknights_Endfield_Icon.png",
    bannerUrl: "https://static.wikia.nocookie.net/arknights/images/1/14/Arknights_Endfield_Key_Visual.png",
    description: "RPG de acción 3D ambientado en Talos-II, un planeta en el universo de Arknights. Combate en tiempo real, exploración y construcción de base.",
    genre: ["RPG de Acción", "Construcción de Base", "Gacha"],
    rating: "12+",
    news: [
      {
        id: "ae-news-1",
        title: "Versión 1.1 en vivo — Tangtang y Rossi debutan en Qingbo Stockade",
        tag: "Nueva versión",
        date: "2026-03-12",
        imageUrl: "https://static.wikia.nocookie.net/arknights/images/1/14/Arknights_Endfield_Key_Visual.png",
        url: "https://endfield.arknights.com/en/news/detail/1055",
      },
      {
        id: "ae-news-2",
        title: "Reinstalación obligatoria del cliente para la versión 1.1",
        tag: "Actualización",
        date: "2026-03-10",
        imageUrl: "https://static.wikia.nocookie.net/arknights/images/1/14/Arknights_Endfield_Key_Visual.png",
        url: "https://endfield.arknights.com/en/news/detail/1040",
      },
      {
        id: "ae-news-3",
        title: "Dev Log Livestream Versión 1.1 — Optimizaciones y nuevo contenido",
        tag: "Retransmisión",
        date: "2026-03-01",
        imageUrl: "https://static.wikia.nocookie.net/arknights/images/1/14/Arknights_Endfield_Key_Visual.png",
        url: "https://endfield.arknights.com/en/news/detail/1020",
      },
      {
        id: "ae-news-4",
        title: "Selector gratuito de personaje 6 estrellas — Disponible ya",
        tag: "Evento",
        date: "2026-02-05",
        imageUrl: "https://static.wikia.nocookie.net/arknights/images/1/14/Arknights_Endfield_Key_Visual.png",
        url: "https://endfield.arknights.com/en/news/detail/0980",
      },
      {
        id: "ae-news-5",
        title: "Arknights: Endfield — Guía de inicio y los mejores Operadores",
        tag: "Guía oficial",
        date: "2026-01-25",
        imageUrl: "https://static.wikia.nocookie.net/arknights/images/1/14/Arknights_Endfield_Key_Visual.png",
        url: "https://endfield.arknights.com/en/news/detail/0920",
      },
      {
        id: "ae-news-6",
        title: "Lanzamiento global exitoso — Arknights: Endfield supera expectativas",
        tag: "Anuncio",
        date: "2026-01-22",
        imageUrl: "https://static.wikia.nocookie.net/arknights/images/1/14/Arknights_Endfield_Key_Visual.png",
        url: "https://endfield.arknights.com/en/news/detail/0900",
      },
    ],
  },

  // ──────────────────────────────────────────────────────────
  // 6. GODDESS OF VICTORY: NIKKE
  // ──────────────────────────────────────────────────────────
  "nikke": {
    id: "nikke",
    name: "Goddess of Victory: NIKKE",
    shortName: "NIKKE",
    developer: "SHIFT UP",
    publisher: "Level Infinite",
    currentVersion: "Parche 19 Mar 2026",
    releaseDate: {
      android: "2022-11-04",
      ios: "2022-11-04",
      pc: "2022-11-04",
    },
    platforms: ["Android", "iOS", "PC"],
    servers: ["Global", "Korea", "Japan"],
    officialSite: "https://nikke-en.com",
    socialLinks: {
      twitter: "https://twitter.com/NIKKE_en",
      youtube: "https://www.youtube.com/@NIKKE_en",
      discord: "https://discord.gg/nikke",
      facebook: "https://www.facebook.com/NIKKEenOfficial",
      instagram: "https://www.instagram.com/nikke_en_official",
      reddit: "https://www.reddit.com/r/NikkeMobile",
    },
    iconUrl: "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/3/33/Item_Goddess_of_Victory_Nikke.png",
    bannerUrl: "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/8/87/Goddess_of_Victory_Nikke_Key_Visual.png",
    description: "Shooter RPG post-apocalíptico donde los Comandantes dirigen a las NIKKE, androides humanas, para recuperar la Tierra de los Rapture.",
    genre: ["Shooter RPG", "Post-apocalíptico", "Gacha"],
    rating: "17+",
    news: [
      {
        id: "nk-news-1",
        title: "Actualización 19 Mar — Arcana: Fortune Mate y evento 2X2 LOVE",
        tag: "Nueva versión",
        date: "2026-03-19",
        imageUrl: "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/8/87/Goddess_of_Victory_Nikke_Key_Visual.png",
        url: "https://nikke-en.com/newsdetail.html?content_id=2x2love2026",
      },
      {
        id: "nk-news-2",
        title: "Colaboración NIKKE x Razer — Skin exclusiva Viper: Punky Street",
        tag: "Colaboración",
        date: "2026-03-19",
        imageUrl: "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/8/87/Goddess_of_Victory_Nikke_Key_Visual.png",
        url: "https://nikke-en.com/newsdetail.html?content_id=razercollab2026",
      },
      {
        id: "nk-news-3",
        title: "Nota del desarrollador Marzo 2026 — Planes para el medio aniversario",
        tag: "Nota del desarrollador",
        date: "2026-03-17",
        imageUrl: "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/8/87/Goddess_of_Victory_Nikke_Key_Visual.png",
        url: "https://nikke-en.com/newsdetail.html?content_id=devnote_march_2026",
      },
      {
        id: "nk-news-4",
        title: "Actualización 5 Mar — E.H. debuta y evento ENTER HEAVEN",
        tag: "Parche",
        date: "2026-03-05",
        imageUrl: "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/8/87/Goddess_of_Victory_Nikke_Key_Visual.png",
        url: "https://nikke-en.com/newsdetail.html?content_id=enterheaven2026",
      },
      {
        id: "nk-news-5",
        title: "Solo Raid Temporada 35 — Guía oficial contra Crystal Chamber",
        tag: "Guía oficial",
        date: "2026-03-20",
        imageUrl: "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/8/87/Goddess_of_Victory_Nikke_Key_Visual.png",
        url: "https://nikke-en.com/newsdetail.html?content_id=soloraid35",
      },
      {
        id: "nk-news-6",
        title: "Champion Arena Beta Temporada 25 — Recompensas y reglas",
        tag: "Evento",
        date: "2026-03-12",
        imageUrl: "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/8/87/Goddess_of_Victory_Nikke_Key_Visual.png",
        url: "https://nikke-en.com/newsdetail.html?content_id=championarena25",
      },
    ],
  },
};

// Listado rápido de todos los juegos (para dropdowns, selectores, etc.)
export const GAMES_LIST = Object.values(GAMES_DATA).map((g) => ({
  id: g.id,
  name: g.name,
  shortName: g.shortName,
  iconUrl: g.iconUrl,
  developer: g.developer,
  currentVersion: g.currentVersion,
  platforms: g.platforms,
}));